### ISSUE TITLE
What are advantages

### ISSUE THREAD

**Issue by roblav96** [kartsims/vue-cordova#1]
I'm confused as to what this does. is it a wrapper/convenience for vue and Cordova?

**Comment by kartsims** [comment]
Absolutely, juste a convenient way to access the API provided by the global `window.cordova` object, and is also meant to be extended to support cordova plugins there.

What do you think ? Does this make sense to you ? Would you use it ?

**Comment by roblav96** [comment]
I do see what you're going for. A comfortable vue developer getting started with Cordova would find this useful.

Great work man!

**Comment by kartsims** [comment]
Thanks :)

**Comment by barryvdh** [comment]
I'm also not really sure what the actual benefit is. It's kind of interesting, but it's difficult that only 4 plugins exists yet.

Compared to http://ngcordova.com/docs/plugins/ which adds Promises etc and more 'angular-ish' stuff, which I'm not really sure what the equivalent would be for Vue.js (not that much experience yet)

Perhaps it would be possible to simply 'automatically' map plugins to the window.cordova.plugins property? So all plugins would be available by default?

**Comment by kartsims** [comment]
I believe each plugin has its own API so loading them all automatically wouldn't work. Plus it is better to implement a bit of documentation for each plugin, so that other developers know how to use and access it.

This lib is actually a work in progress, I was waiting to see if there was any feedback from the community to know if I should keep going.

I agree that the benefit isn't so huge, but it does benefit Vue.js/JS beginners to have a simple approach but a friendly syntax. There has been a few downloads on NPM so I guess some people find it useful.

Next steps would be :

- implement more plugins (based on the list of ngCordova ?)

- get a small static website up using Github Pages, describing the plugins

What do you think would be best to start with ?
