### ISSUE TITLE
.npmignore and /src

### ISSUE THREAD

**Issue by strixy** [kartsims/vue-cordova#6]
.npmignore has /src in it ... I'm new here so maybe I'm missing something, but not having the /src folder makes for an interesting install.

**Comment by kartsims** [comment]
Hi @strixy 

`/src` is in the `.npmignore` file, meaning that it won't be uploaded to npm, because they are source files, not necessary for the end-user. If you `npm install vue-cordova` you will just get the transpiled file (that contains the plugin files).

You can see that by reading the `package.json` file :
- `npm run build` is run before publishing to npm thanks to the `prepublish` script (see the docs)
- `src/index.js` (ES2015) is transpiled to ES5 thanks to webpack (could have done it with Babel only...) to allow support for [older versions of Node](http://node.green/). Result goes to `index.js` (see `webpack.config.js`)
- `main` entry point is `index.js` (and not `src/index.js`)

If you need more explanation, let me know !

**Comment by strixy** [comment]
That was great! Thank you very much.
