### ISSUE TITLE
Device not ready, Plugins array empty ?

### ISSUE THREAD

**Issue by nddr** [kartsims/vue-cordova#9]
When I `console.log(Vue.cordova)` I received this,

> {deviceready: false, plugins: Array[0]}

I have installed phonegap-plugin-barcodescanner, which is what I'm trying to get working. I also have cordova-plugin-crosswalk-webview installed, which seems to be working just fine.

Browser and Android platforms are installed.

Thanks

**Comment by kartsims** [comment]
You need to wait for the `deviceready` event, see README

**Comment by nddr** [comment]
Yes, I've done this and it is never ready. Just sits at false.

**Comment by kartsims** [comment]
Could you please provide an example ? Also there is a repo named [vue-cordova-demo](https://github.com/kartsims/vue-cordova-demo), did you try to clone that and make it work ?

**Comment by nddr** [comment]
I'm looking at the demo now .. I see that `cordova` is a dependency, although if I add `cordova` to my project I get errors, saying there are missing dependencies. I thought cordova cli was only installed globally ...

**Comment by kartsims** [comment]
Did you try the demo and install it as per the README ?

I don't understand why it wouldn't work on your setup while it does on every one else's...

Unless there is something wrong with the library itself, you should post on a QA site such as StackOverflow. It is important to include an example so that other people that know nothing about your particular setup can help.

You can post the link here when you have created the question, I may try to help too.

**Comment by imrealashu** [comment]
Any luck on this ?
